logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:

  data:
    mongodb:
      uri: "mongodb://root:secret@mongodb-svc:27017/urlradar?authSource=admin"

    redis:
      host: localhost

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092