logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE

spring:
  data:
    mongodb:
      uri: "mongodb://root:secret@mongodb-svc:27017/urlradar?authSource=admin"

    redis:
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092