spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  data:
    mongodb:
      uri: "mongodb://root:secret@mongodb-svc:27017/urlradar?authSource=admin"

    redis:
      host: localhost

  kafka:
    bootstrap-servers: http://localhost:9092
