spring:
  application:
    name: urlradar

  data:
    mongodb:
      uri: # This should be overridden based on the specific environment configuration.

    redis:
      host: # This should be overridden based on the specific environment configuration.

  kafka:
    bootstrap-servers: # This should be overridden based on the specific environment configuration.

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
