spring:
  data:
    mongodb:
      uri: "mongodb://root:secret@mongodb-svc:27017/urlradar?authSource=admin"

    redis:
      host: localhost

  kafka:
    bootstrap-servers: http://localhost:9092

rblessings:
  auth-server:
    base-url: http://localhost:9000