logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE

spring:
  application:
    name: urlradar

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: # This should be overridden based on the specific environment configuration.

  data:
    mongodb:
      uri: # This should be overridden based on the specific environment configuration.

    redis:
      host: # This should be overridden based on the specific environment configuration.

  kafka:
    bootstrap-servers: # This should be overridden based on the specific environment configuration.

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
